<?php

/**
 * @file
 * Hook implementations and basic API for Plugins Example module.
 */

use \Drupal\plugins_example\Plugin\Action\ActionManager;
use \Drupal\plugins_example\Plugin\Name\NameManager;

/**
 * Implements hook_plugins_info().
 */
function plugins_example_plugins_info() {
  return array(
    'example_action' => array(
      'namespace' => 'Plugin\Action',
    ),
  );
}

/**
 * Implements hook_plugins_info_alter().
 */
function plugins_example_plugins_info_alter(&$info) {
  $info['example_name'] = array(
    'namespace' => 'Plugin\Name',
  );
}

/**
 * Implements hook_menu().
 */
function plugins_example_menu() {
  $items = array();

  $items['admin/config/plugins_example'] = array(
    'title' => 'Test Person actions',
    'page callback' => 'plugins_example_action_test_page',
    'access arguments' => array('access content'),
  );
  $items['admin/config/plugins_example/actions'] = array(
    'title' => 'Test Person actions',
    'page callback' => 'plugins_example_action_test_page',
    'access arguments' => array('access content'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );

  $items['admin/config/plugins_example/names'] = array(
    'title' => 'Test Person names',
    'page callback' => 'plugins_example_name_test_page',
    'access arguments' => array('access content'),
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Plugins example page callback.
 */
function plugins_example_action_test_page() {
  $output = 'Performing actions...<br />';
  $action_manager = new ActionManager();

  foreach ($action_manager->getPluginInstances() as $instance) {
    /** @var $instance \Drupal\plugins_example\Plugin\Action\ActionInterface */
    $output .= $instance->performAction() . '<br />';
  }

  return $output . 'Actions performed';
}

/**
 * Plugins example page callback.
 */
function plugins_example_name_test_page() {
  plugins_get_info();
  $output = 'Loading names...<br />';
  $action_manager = new NameManager();

  foreach ($action_manager->getPluginInstances() as $instance) {
    /** @var $instance \Drupal\plugins_example\Plugin\Name\NameInterface */
    $output .= $instance->tellName() . '<br />';
  }

  return $output . 'Names loaded';
}
